### ISSUE TITLE
MYS - 146 - STP - SOP API - Lumbar Spondylosis - Error occured when user has service type is Active Reserve Force

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-sop-api#25]
Submitted a request with User having following service types on different dates

"serviceType": "Regular/Permanent Force",

"serviceType": "Active Reserve Force",

Actual Response:

Request is not accepted

Expected Response:

Request should be accepted

Attachments:

Please refer to the attached request and response messages for details

{
	"condition": {
		"conditionName": "lumbar spondylosis",
		"incidentType": "onset",
		"icdCodeVersion": null,
		"icdCodeValue": null,
		"onsetDates": {
			"onsetRangeStartDate": "2009-11-11T00:00:00+11:00",
			"onsetRangeEndDate": "2009-11-11T00:00:00+11:00"
		},
		"aggravationDates": null
	},
	"serviceHistory": {
		"serviceSummaryInformation": {
			"originalHireDate": "2004-10-10T00:00:00+10:00"
		},
		"serviceDetails": [{
			"serviceType": "Regular/Permanent Force",
			"startDate": "2007-04-10T00:00:00+10:00",
			"endDate": "2013-04-14T00:00:00+10:00",
			"rank": "officer",
			"operationalService": [{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Force Preparation Training",
				"startDate": "2009-10-19T00:00:00+11:00",
				"endDate": "2009-10-23T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Departure",
				"startDate": "2009-11-17T00:00:00+11:00",
				"endDate": null
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2009-11-18T00:00:00+11:00",
				"endDate": "2010-01-02T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-01-03T00:00:00+11:00",
				"endDate": "2010-01-05T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-01-06T00:00:00+11:00",
				"endDate": "2010-02-25T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-02-26T00:00:00+11:00",
				"endDate": "2010-02-27T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-02-28T00:00:00+11:00",
				"endDate": "2010-03-17T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "RTA Psychological Screening",
				"startDate": "2010-03-15T00:00:00+11:00",
				"endDate": null
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Pst Op Psychological Screening",
				"startDate": "2010-06-16T00:00:00+10:00",
				"endDate": null
			}],
			"service": "Australian Army"
		},
		{
			"serviceType": "Active Reserve Force",
			"startDate": "2013-04-15T00:00:00+10:00",
			"endDate": null,
			"rank": "officer",
			"operationalService": [],
			"service": "Australian Army"
		}]
	}
}

<data contentType="text/plain;charset=utf-8" contentLength="7604"><![CDATA[com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type au.gov.dva.sopapi.dtos.EmploymentType from String "Active Reserve Force": value not one of declared Enum instance names: [Non-Regular/Permanent Force, Regular/Permanent Force]
 at [Source: {
	"condition": {
		"conditionName": "lumbar spondylosis",
		"incidentType": "onset",
		"icdCodeVersion": null,
		"icdCodeValue": null,
		"onsetDates": {
			"onsetRangeStartDate": "2009-11-11T00:00:00+11:00",
			"onsetRangeEndDate": "2009-11-11T00:00:00+11:00"
		},
		"aggravationDates": null
	},
	"serviceHistory": {
		"serviceSummaryInformation": {
			"originalHireDate": "2004-10-10T00:00:00+10:00"
		},
		"serviceDetails": [{
			"serviceType": "Regular/Permanent Force",
			"startDate": "2007-04-10T00:00:00+10:00",
			"endDate": "2013-04-14T00:00:00+10:00",
			"rank": "officer",
			"operationalService": [{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Force Preparation Training",
				"startDate": "2009-10-19T00:00:00+11:00",
				"endDate": "2009-10-23T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Departure",
				"startDate": "2009-11-17T00:00:00+11:00",
				"endDate": null
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2009-11-18T00:00:00+11:00",
				"endDate": "2010-01-02T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-01-03T00:00:00+11:00",
				"endDate": "2010-01-05T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-01-06T00:00:00+11:00",
				"endDate": "2010-02-25T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-02-26T00:00:00+11:00",
				"endDate": "2010-02-27T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Within Specified Area",
				"startDate": "2010-02-28T00:00:00+11:00",
				"endDate": "2010-03-17T00:00:00+11:00"
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "RTA Psychological Screening",
				"startDate": "2010-03-15T00:00:00+11:00",
				"endDate": null
			},
			{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Pst Op Psychological Screening",
				"startDate": "2010-06-16T00:00:00+10:00",
				"endDate": null
			}],
			"service": "Australian Army"
		},
		{
			"serviceType": "Active Reserve Force",
			"startDate": "2013-04-15T00:00:00+10:00",
			"endDate": null,
			"rank": "officer",
			"operationalService": [],
			"service": "Australian Army"
		}]
	}
}; line: 88, column: 19] (through reference chain: au.gov.dva.sopapi.dtos.sopsupport.SopSupportRequestDto["serviceHistory"]->au.gov.dva.sopapi.dtos.sopsupport.components.ServiceHistoryDto["serviceDetails"]->java.util.ArrayList[1]->au.gov.dva.sopapi.dtos.sopsupport.components.ServiceDto["serviceType"])Request must conform to schema:
Optional[{
  "type" : "object",
  "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:SopSupportRequestDto",
  "properties" : {
    "condition" : {
      "type" : "object",
      "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:ConditionDto",
      "required" : true,
      "properties" : {
        "conditionName" : {
          "type" : "string",
          "required" : true
        },
        "incidentType" : {
          "type" : "string",
          "required" : true,
          "enum" : [ "onset", "aggravation" ]
        },
        "icdCodeVersion" : {
          "type" : "string"
        },
        "icdCodeValue" : {
          "type" : "string"
        },
        "onsetDates" : {
          "type" : "object",
          "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:OnsetDateRangeDto",
          "properties" : {
            "onsetRangeStartDate" : {
              "type" : "any"
            },
            "onsetRangeEndDate" : {
              "type" : "any"
            }
          }
        },
        "aggravationDates" : {
          "type" : "object",
          "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:AggravationDateRangeDto",
          "properties" : {
            "aggravationRangeStartDate" : {
              "type" : "any"
            },
            "aggravationRangeEndDate" : {
              "type" : "any"
            }
          }
        }
      }
    },
    "serviceHistory" : {
      "type" : "object",
      "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:ServiceHistoryDto",
      "required" : true,
      "properties" : {
        "serviceSummaryInformation" : {
          "type" : "object",
          "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:ServiceSummaryInfoDto",
          "required" : true,
          "properties" : {
            "originalHireDate" : {
              "type" : "any",
              "required" : true
            }
          }
        },
        "serviceDetails" : {
          "type" : "array",
          "required" : true,
          "items" : {
            "type" : "object",
            "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:ServiceDto",
            "properties" : {
              "serviceType" : {
                "type" : "string",
                "required" : true,
                "enum" : [ "Regular/Permanent Force", "Non-Regular/Permanent Force" ]
              },
              "startDate" : {
                "type" : "any",
                "required" : true
              },
              "endDate" : {
                "type" : "any"
              },
              "rank" : {
                "type" : "string",
                "enum" : [ "officer", "other rank", "special forces", "unknown" ]
              },
              "operationalService" : {
                "type" : "array",
                "required" : true,
                "items" : {
                  "type" : "object",
                  "id" : "urn:jsonschema:au:gov:dva:sopapi:dtos:sopsupport:components:OperationalServiceDto",
                  "properties" : {
                    "assigned" : {
                      "type" : "any"
                    },
                    "description" : {
                      "type" : "string",
                      "required" : true
                    },
                    "event" : {
                      "type" : "string",
                      "required" : true
                    },
                    "startDate" : {
                      "type" : "any",
                      "required" : true
                    },
                    "endDate" : {
                      "type" : "any"
                    }
                  }
                }
              },
              "service" : {
                "type" : "string",
                "required" : true,
                "enum" : [ "Australian Army", "Royal Australian Navy", "Royal Australian Air Force" ]
              }
            }
          }
        }
      }
    }
  }
}]]]></data>

**Comment by nicholasamiller** [comment]
I don't see a bug here.  The schema for the request in the error message says the Service type has to be: "Regular/Permanent Force" or "Non-Regular/Permanent Force".  So if anything else is sent, there should be an error. 
MyService should map Active Reserves to the 'Non-Regular/Permanent Force' value in the request.  Alternatively, MyService could simply not send any objects for service type which is not Regular/Permanent Force.

**Comment by michael-ctr** [comment]
Should it though? How is my service to know that "Active Reserve Force" Means "Non-Regular/Permanent Force". I think we need to know the complete schema of what values PMKEYS is going to produce here

**Comment by nicholasamiller** [comment]
What about if we change SoP to dispatch with the EmploymentType enum and instead match on the string value? If it is 'Regular/Permanent Force', we count that towards the calculation of CFTS.  Otherwise not.  That way no additional logic is needed in MyService.  Who knows, in future other service types might be important!  (I have read all the specification documents I could get my hands on for the PMKeyS interface, and also the WSDL schema - no restriction on  values.)

**Comment by michael-ctr** [comment]
Yeah, that probably makes the most sense. It's a bit weird that we can't tell what those values are though. Seems like you need to understand what they could be to make a sensible decision

**Comment by nicholasamiller** [comment]
Great idea!  Assigned to you to address.  I have labelled it as an 'enhancement' rather than a bug as currently there is no wrong result for claim being returned.  The issue is more about neater integration.

**Comment by nicholasamiller** [comment]
This issue was moved to govlawtech/dva-sop-api-issues#4
