### ISSUE TITLE
MYS- 145 STP - SOP API - Lumbar Spondylosis - Claim is accepted for a Client who has operational service which is not WSA [SEC=UNOFFICIAL]

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dva-sop-api#28]
Hi

 

Description:

Claim is accepted for an operational service without WSA event

Request data is as below:

 

"operationalService": [{
    "assigned": "2009-11-11T00:00:00+11:00",
    "description": "Operation SLIPPER",
    "event": "Departure",
    "startDate": "2011-12-01",
    "endDate": "2011-12-29"
   }],

Actual Response:

"recommendation": "Accept claim",

 

Expected Response:

Claim should be accepted for operations with only Within specified area event type

 

Attachments:

Please refer to the attached request and response messages for details

 

 

 

 Thanks,

Kiran

 

 

 

 

 
IMPORTANT
1. Before opening any attachments, please check for viruses.
2. This e-mail (including any attachments) may contain confidential information
for the intended recipient. If you are not the intended recipient,
please contact the sender and delete all copies of this email.
3. Any views expressed in this e-mail are those of the sender and are not
a statement of Australian Government Policy unless otherwise stated.
4. Electronic addresses published in this email are not conspicuous publications and DVA does not consent to the receipt of commercial electronic messages.
5. To unsubscribe from emails from the Department of Veterans' Affairs (DVA) please go to
http://www.dva.gov.au/contact_us/Pages/feedback.aspx
, and advise which mailing list you would like to unsubscribe from.
6. Finally, please do not remove this notice.

request_RH Met&BOP Met.json.txt

{
	"condition": {
		"conditionName": "lumbar spondylosis",
		"incidentType": "onset",
		"icdCodeVersion": null,
		"icdCodeValue": null,
		"onsetDates": {
			"onsetRangeStartDate": "2012-09-16",
			"onsetRangeEndDate": "2012-09-16"
		},
		"aggravationDates": null
	},
	"serviceHistory": {
		"serviceSummaryInformation": {
			"originalHireDate": "2011-12-28"
		},
		"serviceDetails": [{
			"serviceType": "Regular/Permanent Force",
			"startDate": "2011-10-10",
			"endDate": "2012-09-16",
			"rank": "Officer",
			"operationalService": [{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Departure",
				"startDate": "2011-12-01",
				"endDate": "2011-12-29"
			}],

			"service": "Australian Army"
		}]
	}
}

response_RH Met&BOP Met.json.txt

{
  "applicableInstrument" : {
    "registerId" : "F2014L00933",
    "instrumentNumber" : "62/2014",
    "citation" : "Statement of Principles concerning lumbar spondylosis No. 62 of 2014",
    "effectiveFromDate" : "2014-07-02",
    "standardOfProof" : "Reasonable Hypothesis"
  },
  "factors" : [ {
    "paragraph" : "6(a)",
    "text" : "being a prisoner of war before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(b)",
    "text" : "having inflammatory joint disease in the lumbar spine before the\r\nclinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "inflammatory joint disease",
      "definition" : "means rheumatoid arthritis, reactive arthritis,\npsoriatic arthropathy, ankylosing spondylitis, or arthritis associated with\nCrohn's disease or ulcerative colitis"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(c)",
    "text" : "having an infection of the affected joint as specified at least one year\r\nbefore the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "an infection of the affected joint as specified",
      "definition" : "means bacterial or fungal\ninfection of the affected joint in the lumbar spine resulting in inflammation\nwithin that joint"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(d)",
    "text" : "having an intra-articular fracture of the lumbar spine at least one year\r\nbefore the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "an intra-articular fracture",
      "definition" : "means a fracture involving any articular surface\nof the affected joint"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(e)",
    "text" : "having a specified spinal condition affecting the lumbar spine for at\r\nleast the one year before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "a specified spinal condition",
      "definition" : "means:\n(a) a deformity of a joint of a vertebra;\n(b) a deformity of a vertebra;\n(c) a kyphotic abnormality;\n(d) a lordotic abnormality;\n(e) necrosis of bone;\n(f) retrospondylolisthesis;\n(g) scoliosis; or\n(h) spondylolisthesis"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(f)",
    "text" : "having leg length inequality for at least the two years before the clinical\r\nonset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "leg length inequality",
      "definition" : "means a clinically significant disparity of at least\nthree percent or three centimetres in leg length, whichever is the lesser, where\nthe inequality remains uncorrected and involves the limb in daily use"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(g)",
    "text" : "having a depositional joint disease in the lumbar spine before the\r\nclinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "a depositional joint disease",
      "definition" : "means gout, calcium pyrophosphate dihydrate\ndeposition disease (also known as pseudogout), haemochromatosis, Wilson's\ndisease or alkaptonuria (also known as ochronosis)"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(h)",
    "text" : "having trauma to the lumbar spine at least one year before the clinical\r\nonset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "trauma to the lumbar spine",
      "definition" : "means a discrete event involving the\napplication of significant physical force, including G force, to the lumbar spine\nthat causes the development within twenty-four hours of the injury being\nsustained, of symptoms and signs of pain and tenderness and either altered\nmobility or range of movement of the lumbar spine. In the case of sustained\nunconsciousness or the masking of pain by analgesic medication, these\nsymptoms and signs must appear on return to consciousness or the withdrawal\nof the analgesic medication. These symptoms and signs must last for a period\nof at least seven days following their onset; save for where medical\nintervention has occurred and that medical intervention involves either:\n(a) immobilisation of the lumbar spine by splinting, or similar external\nagent;\n(b) injection of corticosteroids or local anaesthetics into the lumbar spine; or\n(c) surgery to the lumbar spine"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(i)",
    "text" : "having a lumbar intervertebral disc prolapse before the clinical onset of\r\nlumbar spondylosis at the level of the intervertebral disc prolapse",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(j)",
    "text" : "lifting loads of at least 25 kilograms while bearing weight through the\r\nlumbar spine to a cumulative total of at least 120 000 kilograms within\r\nany ten year period before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "lifting loads",
      "definition" : "means manually raising an object"
    } ],
    "satisfied" : true
  }, {
    "paragraph" : "6(k)",
    "text" : "carrying loads of at least 25 kilograms while bearing weight through\r\nthe lumbar spine to a cumulative total of at least 3 800 hours within\r\nany ten year period before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(l)",
    "text" : "being obese for at least ten years before the clinical onset of lumbar\r\nspondylosis",
    "definedTerms" : [ {
      "term" : "being obese",
      "definition" : "means an increase in body weight by way of fat accumulation\nwhich results in a Body Mass Index (BMI) of thirty or greater.\n2\nThe BMI = W/H and where:\nW is the person's weight in kilograms; and\nH is the person's height in metres"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(m)",
    "text" : "flying in a powered aircraft as operational aircrew, for a cumulative\r\ntotal of at least 1 000 hours within the 25 years before the clinical onset\r\nof lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(n)",
    "text" : "extreme forward flexion of the lumbar spine for a cumulative total of at\r\nleast 1 500 hours before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "extreme forward flexion of the lumbar spine",
      "definition" : "means being in a posture\ninvolving greater than 90 degrees of trunk flexion"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(o)",
    "text" : "having acromegaly involving the lumbar spine before the clinical onset\r\nof lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(p)",
    "text" : "having Paget's disease of bone involving the lumbar spine before the\r\nclinical onset of lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  } ],
  "recommendation" : "Accept claim",
  "caseTrace" : {
    "standardOfProof" : "Reasonable Hypothesis",
    "requiredDaysOfCfts" : 343,
    "requiredDaysOfCftsForRh" : 343,
    "requiredDaysOfCftsForBop" : 357,
    "actualDaysOfCfts" : 343,
    "requiredDaysOfOperationalServiceForRhStandard" : 28,
    "actualDaysOfOperationalServiceInTestPeriod" : 28,
    "rhFactors" : [ {
      "paragraph" : "6(j)",
      "text" : "lifting loads of at least 25 kilograms while bearing weight through the\r\nlumbar spine to a cumulative total of at least 120 000 kilograms within\r\nany ten year period before the clinical onset of lumbar spondylosis",
      "definedTerms" : [ {
        "term" : "lifting loads",
        "definition" : "means manually raising an object"
      } ]
    } ],
    "bopFactors" : [ {
      "paragraph" : "6(i)",
      "text" : "lifting loads of at least 35 kilograms while bearing weight through the\r\nlumbar spine to a cumulative total of at least 168 000 kilograms within\r\nany ten year period before the clinical onset of lumbar spondylosis, and\r\nwhere the clinical onset of lumbar spondylosis occurs within the 25\r\nyears following that period",
      "definedTerms" : [ {
        "term" : "lifting loads",
        "definition" : "means manually raising an object"
      } ]
    } ],
    "reasonings" : {
      "MEETING_FACTORS" : [ "Required days of continuous full time service: 343", "Actual days of continuous full time service: 343" ],
      "STANDARD_OF_PROOF" : [ "Required number of days of operational service for Reasonable Hypothesis: 28.", "Actual number of days of operational service: 28." ]
    },
    "logTrace" : "Case ID: ab979964-6496-4b1a-b8a1-7061f106d94f\r\nThe start date for the test period of operational service is the start of the earliest operational service: 2011-12-01T00:00+11:00\r\nThe end date for the test period of operational service is the condition start date: 2012-09-16T00:00+10:00\r\nRequired number of days of operational service for Reasonable Hypothesis: 28.\r\nActual number of days of operational service: 28.\r\nThe RH SoP is applicable as the actual number of days of operational service in the test period is greater than or equal to the required number.\r\nApplicable SoP is Statement of Principles concerning lumbar spondylosis No. 62 of 2014\r\nThere are 16 factors in the applicable SoP: Statement of Principles concerning lumbar spondylosis No. 62 of 2014.\r\nRequired days of continuous full time service: 343\r\nActual days of continuous full time service: 343\r\nActual number of days of continuous full time service is at least the required days.  According to configuration, the applicable factors are '6(j), 6(y)'.\r\n"
  }
}

request_RH Met&BOP Met.json.txt

{
	"condition": {
		"conditionName": "lumbar spondylosis",
		"incidentType": "onset",
		"icdCodeVersion": null,
		"icdCodeValue": null,
		"onsetDates": {
			"onsetRangeStartDate": "2012-09-16",
			"onsetRangeEndDate": "2012-09-16"
		},
		"aggravationDates": null
	},
	"serviceHistory": {
		"serviceSummaryInformation": {
			"originalHireDate": "2011-12-28"
		},
		"serviceDetails": [{
			"serviceType": "Regular/Permanent Force",
			"startDate": "2011-10-10",
			"endDate": "2012-09-16",
			"rank": "Officer",
			"operationalService": [{
				"assigned": "2009-11-11T00:00:00+11:00",
				"description": "Operation SLIPPER",
				"event": "Departure",
				"startDate": "2011-12-01",
				"endDate": "2011-12-29"
			}],

			"service": "Australian Army"
		}]
	}
}

response_RH Met&BOP Met.json.txt

{
  "applicableInstrument" : {
    "registerId" : "F2014L00933",
    "instrumentNumber" : "62/2014",
    "citation" : "Statement of Principles concerning lumbar spondylosis No. 62 of 2014",
    "effectiveFromDate" : "2014-07-02",
    "standardOfProof" : "Reasonable Hypothesis"
  },
  "factors" : [ {
    "paragraph" : "6(a)",
    "text" : "being a prisoner of war before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(b)",
    "text" : "having inflammatory joint disease in the lumbar spine before the\r\nclinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "inflammatory joint disease",
      "definition" : "means rheumatoid arthritis, reactive arthritis,\npsoriatic arthropathy, ankylosing spondylitis, or arthritis associated with\nCrohn's disease or ulcerative colitis"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(c)",
    "text" : "having an infection of the affected joint as specified at least one year\r\nbefore the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "an infection of the affected joint as specified",
      "definition" : "means bacterial or fungal\ninfection of the affected joint in the lumbar spine resulting in inflammation\nwithin that joint"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(d)",
    "text" : "having an intra-articular fracture of the lumbar spine at least one year\r\nbefore the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "an intra-articular fracture",
      "definition" : "means a fracture involving any articular surface\nof the affected joint"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(e)",
    "text" : "having a specified spinal condition affecting the lumbar spine for at\r\nleast the one year before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "a specified spinal condition",
      "definition" : "means:\n(a) a deformity of a joint of a vertebra;\n(b) a deformity of a vertebra;\n(c) a kyphotic abnormality;\n(d) a lordotic abnormality;\n(e) necrosis of bone;\n(f) retrospondylolisthesis;\n(g) scoliosis; or\n(h) spondylolisthesis"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(f)",
    "text" : "having leg length inequality for at least the two years before the clinical\r\nonset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "leg length inequality",
      "definition" : "means a clinically significant disparity of at least\nthree percent or three centimetres in leg length, whichever is the lesser, where\nthe inequality remains uncorrected and involves the limb in daily use"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(g)",
    "text" : "having a depositional joint disease in the lumbar spine before the\r\nclinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "a depositional joint disease",
      "definition" : "means gout, calcium pyrophosphate dihydrate\ndeposition disease (also known as pseudogout), haemochromatosis, Wilson's\ndisease or alkaptonuria (also known as ochronosis)"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(h)",
    "text" : "having trauma to the lumbar spine at least one year before the clinical\r\nonset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "trauma to the lumbar spine",
      "definition" : "means a discrete event involving the\napplication of significant physical force, including G force, to the lumbar spine\nthat causes the development within twenty-four hours of the injury being\nsustained, of symptoms and signs of pain and tenderness and either altered\nmobility or range of movement of the lumbar spine. In the case of sustained\nunconsciousness or the masking of pain by analgesic medication, these\nsymptoms and signs must appear on return to consciousness or the withdrawal\nof the analgesic medication. These symptoms and signs must last for a period\nof at least seven days following their onset; save for where medical\nintervention has occurred and that medical intervention involves either:\n(a) immobilisation of the lumbar spine by splinting, or similar external\nagent;\n(b) injection of corticosteroids or local anaesthetics into the lumbar spine; or\n(c) surgery to the lumbar spine"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(i)",
    "text" : "having a lumbar intervertebral disc prolapse before the clinical onset of\r\nlumbar spondylosis at the level of the intervertebral disc prolapse",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(j)",
    "text" : "lifting loads of at least 25 kilograms while bearing weight through the\r\nlumbar spine to a cumulative total of at least 120 000 kilograms within\r\nany ten year period before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "lifting loads",
      "definition" : "means manually raising an object"
    } ],
    "satisfied" : true
  }, {
    "paragraph" : "6(k)",
    "text" : "carrying loads of at least 25 kilograms while bearing weight through\r\nthe lumbar spine to a cumulative total of at least 3 800 hours within\r\nany ten year period before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(l)",
    "text" : "being obese for at least ten years before the clinical onset of lumbar\r\nspondylosis",
    "definedTerms" : [ {
      "term" : "being obese",
      "definition" : "means an increase in body weight by way of fat accumulation\nwhich results in a Body Mass Index (BMI) of thirty or greater.\n2\nThe BMI = W/H and where:\nW is the person's weight in kilograms; and\nH is the person's height in metres"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(m)",
    "text" : "flying in a powered aircraft as operational aircrew, for a cumulative\r\ntotal of at least 1 000 hours within the 25 years before the clinical onset\r\nof lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(n)",
    "text" : "extreme forward flexion of the lumbar spine for a cumulative total of at\r\nleast 1 500 hours before the clinical onset of lumbar spondylosis",
    "definedTerms" : [ {
      "term" : "extreme forward flexion of the lumbar spine",
      "definition" : "means being in a posture\ninvolving greater than 90 degrees of trunk flexion"
    } ],
    "satisfied" : false
  }, {
    "paragraph" : "6(o)",
    "text" : "having acromegaly involving the lumbar spine before the clinical onset\r\nof lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  }, {
    "paragraph" : "6(p)",
    "text" : "having Paget's disease of bone involving the lumbar spine before the\r\nclinical onset of lumbar spondylosis",
    "definedTerms" : [ ],
    "satisfied" : false
  } ],
  "recommendation" : "Accept claim",
    "rhFactors" : [ {
      "paragraph" : "6(j)",
      "text" : "lifting loads of at least 25 kilograms while bearing weight through the\r\nlumbar spine to a cumulative total of at least 120 000 kilograms within\r\nany ten year period before the clinical onset of lumbar spondylosis",
      "definedTerms" : [ {
        "term" : "lifting loads",
        "definition" : "means manually raising an object"
      } ]
    } ],
    "bopFactors" : [ {
      "paragraph" : "6(i)",
      "text" : "lifting loads of at least 35 kilograms while bearing weight through the\r\nlumbar spine to a cumulative total of at least 168 000 kilograms within\r\nany ten year period before the clinical onset of lumbar spondylosis, and\r\nwhere the clinical onset of lumbar spondylosis occurs within the 25\r\nyears following that period",
      "definedTerms" : [ {
        "term" : "lifting loads",
        "definition" : "means manually raising an object"
      } ]
    } ],
    "reasonings" : {
      "MEETING_FACTORS" : [ "Required days of continuous full time service: 343", "Actual days of continuous full time service: 343" ],
      "STANDARD_OF_PROOF" : [ "Required number of days of operational service for Reasonable Hypothesis: 28.", "Actual number of days of operational service: 28." ]
    },
    "logTrace" : "Case ID: ab979964-6496-4b1a-b8a1-7061f106d94f\r\nThe start date for the test period of operational service is the start of the earliest operational service: 2011-12-01T00:00+11:00\r\nThe end date for the test period of operational service is the condition start date: 2012-09-16T00:00+10:00\r\nRequired number of days of operational service for Reasonable Hypothesis: 28.\r\nActual number of days of operational service: 28.\r\nThe RH SoP is applicable as the actual number of days of operational service in the test period is greater than or equal to the required number.\r\nApplicable SoP is Statement of Principles concerning lumbar spondylosis No. 62 of 2014\r\nThere are 16 factors in the applicable SoP: Statement of Principles concerning lumbar spondylosis No. 62 of 2014.\r\nRequired days of continuous full time service: 343\r\nActual days of continuous full time service: 343\r\nActual number of days of continuous full time service is at least the required days.  According to configuration, the applicable factors are '6(j), 6(y)'.\r\n"
  }
}

**Comment by michael-ctr** [comment]
Seems like a straight forward requirements question. Which 'events' count towards service for STP purposes? Someone needs to answer that before this can be progessed

**Comment by nicholasamiller** [comment]
I think it is only 'Within Specified Area' area events.  The specified area is the one referred to in the Service Determinations of warlike and non-warlike operations.  They actually have a column called 'specified area', often with lat and long coordinates.

**Comment by nicholasamiller** [comment]
This issue was moved to govlawtech/dva-sop-api-issues#1

**Comment by nicholasamiller** [comment]
This issue was moved to govlawtech/dva-sop-api-issues#2
